### ISSUE TITLE
Overlay shape files onto the map

### ISSUE THREAD

**Issue by dpkeesling** [dpkeesling/WMASS#33]

**Comment by alexleroyross** [comment]
There's a library that allows you to do this which I think I pretty much got totally set up.  The only issue I'm facing right now is that accessing the shapefiles is blocked by CORS policy since they have to be hosted on a local server.  This is annoying, but once I figure out how to fix it, this ticket should be good to go.

**Comment by alexleroyross** [comment]
Got it working.  Just need to discuss a couple of quirks in the code with the group on Monday.

**Comment by alexleroyross** [comment]
Before I put this up for PR, I will get this working on Windows IIS rather than a SimpleHTTPServer through Python.  Should be up for PR by the end of the day!

**Comment by alexleroyross** [comment]
The PR is merged and everything works fine when I use Windows IIS on my local machine.  However, it for some reason doesn't seem to be working in our GitHub deployment, so I'm going to try and investigate that.  I'm not currently using jQuery to load the shapefiles (unlike how Dan loads in the JSON map data) so I'm going to try that and see if that works.  I will try to have an update by the end of the day.

**Comment by alexleroyross** [comment]
Forgot to update this ticket.  The shapefiles work correctly when I run this on my Windows machine, so I'm not sure why they don't work in our GitHub deployment.  Either way, this is finished so I'm closing this
